apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calibre
  name: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      volumes:
        - name: calibre-config
          persistentVolumeClaim:
            claimName: calibre-config-pvc
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-data-pvc
        - name: calibre-ingest
          persistentVolumeClaim:
            claimName: calibre-ingest-pvc
      containers:
      - image: crocodilestick/calibre-web-automated:v4.0.6
        name: calibre
        ports:
          - containerPort: 8083
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: "/config"
            name: calibre-config
          - mountPath: "/calibre-library"
            name: calibre-data
