apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
