apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7SeIMbwylY34HxNboET/lLnOh3QgQ50j,iv:Fpwt/N5QohXNT3ZPiXBU3DYQRJWBE3EkZ6FWGbBuTdU=,tag:5WEObzj8XkCWKW8PnAQ36g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:nGopU3hMJGY=,iv:AFTWUQKX/mAtnBsE7i3V6nREtcqan6MvjCjPJ0GYexA=,tag:AMGDX0gShERn/Yw0jyJSnQ==,type:str]
kind: Secret
metadata:
    name: postgres-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURk92MnlKNVZiUm5JUmR4
            RldKYUUyZ3RyV3EzTURJcElLRHNScVNReGdRCm01eGVLR2ZGV0NVdk1oSndpa0hs
            WjVnWDM4eFc4N2NwL29JRlhVWXB1dkkKLS0tIGxzTWIxRFZOcmY1RzhJNmVyRTBw
            Z0NIS05CSnROWldhZHJEdWhBVDVjU0UKaCBDHF4yfhenTnxqWcq9WKBm8C8n3aHz
            6075tS9vA2ayDT7e2OEkBbLUElYRQzKultJoEnOdiuhMynSYLFdFrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T19:20:47Z"
    mac: ENC[AES256_GCM,data:nk8WrLxK3UtrFD0Hg6Sb+wdl3QzoLt/Ev4+PVMJxC1Zl4NbOLCj8/O+NG2OS46O9+wbNEUJcQYaOeBTnOX4sYQXJ8GDBE6sTqdhYhkB0jHXtRqG51DYhGEE5P/l0gnfdowH6c/E58HbwBBlvykmy3FDGqBW1meKxk3pITpAlzRc=,iv:deDhqkx87NMds4qbKwWu741PQ3ov9yh3ScdNRTl9wec=,tag:zm52bebkqY4JnPll+yAQWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
