apiVersion: v1
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:zYtDZjgNtvOloI8UpmHaZ7M5DhavWliUrsDb8Hg0C6jyRlHIBOAxSA==,iv:iCSdXKnWGMjmmNZVykYekY9UtqkkvcHE1P10J2Az+nM=,tag:UrzVRurMP3WNXvAaWBdb1w==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:C1u312OxV8TpjoBea05kbtLX2SiwEyVh,iv:6wwwk+JI5YHxaJhjLjO9K8u0QDnUdQy2k1V0Heeg8a0=,tag:kVSpnBnt+V24QeoZGklHFg==,type:str]
kind: Secret
metadata:
    name: pgadmin-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4U29UUmtqbm5ENVZOSHE5
            SEcvN3dVNnNNMlhhZmlubkYxeUYxdzBDREJvCnlFQk5YbkVrQ0t0czhPaVEzSkx4
            c2M5SEdveVlxV1d2N2lkWjNEMFgxSXcKLS0tIEtId2JJZmZzd0tiTmFsQ2NqcVJR
            a2JpeEdYUzlEM3JybEpZamUxSXQ1UEUKedIZ6hbGAEEJQiCdeoSxR39EwX7hoHDc
            oPK2R6ecXDmyEo+atlQWl+8sulY5tJEacsuFMdJ6GhiosSAEZoz35g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T19:27:29Z"
    mac: ENC[AES256_GCM,data:FYIRzq0X6eyrA1jMkdloUt1qdJRRaAs+AqzSVv9hChsmFUdad0dDhaYb/uQKq+KmZlWKPi+CX8kv1CPnU2Rvnons1XsTTvumB9GvB7IaSHsvbxnLIQIdKZPTV/pSsjQDJQYy1uKPNzXrYF65jQkIKytAAKyKRBwpKTIxenhGFgM=,iv:ZVrbQbIqKQcFtGyjwSJ7PVNtSxV/ZyyZJpYSc26a+UQ=,tag:50hXa+y2Zz99ynN9nqhOSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
