apiVersion: v1
data:
    LD_DB_DATABASE: ENC[AES256_GCM,data:I1ODO/fJu9+qE/xV,iv:DGpU25XDs+UHK4MscGf4jcEOj0mzTje388fDMae93po=,tag:ONRWL3s/nmjC/qVbCd4zNQ==,type:str]
    LD_DB_ENGINER: ENC[AES256_GCM,data:kXa7bfiL+DI99lpX,iv:n+XzOGCNG4lU46gqcH7t/NFg2sIGeld0ltd7FP4tgYQ=,tag:CFlSPq7/nkk45ykOfIKWNA==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:0MMaeCSZDe/t/xBOxv6r0SbfB2nwiyj/udK/gxsUy40=,iv:AG2RxNtpO6usZQmFmlN7jEO99Nd+5fl7NTn7T9Ji5R4=,tag:foa2ba7tvaFkQTyGFfnNzQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:4v32vXwd+CmQ2MnR33nNXElSs63FbgIQ,iv:w2sUkrTYpLDVBtoh6L0USO6Prn4w6FBpfngu/xMkhvM=,tag:pjCjHy3fTWH3nEEd/FYEew==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:7nQ26n3WwYU=,iv:FzWRcDorxzlpR6Vvo/Ub1paOALugZrlIMlq4J3VNrT8=,tag:WA25cDPBOvH2tlAdjwoMsg==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:xdSbsRk9q3OGV8bT,iv:UmDbMvKqjlNoRY0aARHvKhOPjUki7F4dVsTJJXKkIec=,tag:zi0G1SfVFFfm3El6mJ54nw==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Wx7cIXSSkSE=,iv:SuXEqFFlR2QxQI7Trb/MY11LsduHqoPW245M7GGiF5w=,tag:s6rKublmFb1X2xEKaVanng==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:yBv719Ek3XsZBQsM0S/Gyh1R4Ec9K9gM,iv:ugxOQ8DFEJjsiKeKJIrk8muXEL67GT7xOXN9bsbqYe4=,tag:TKmC9zWr7ExmNObFg5x+IA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROFIyRGJYMllCZUFCUXRD
            Q01TbWRWZ01HMTFsZzNsemNRZU5ySHVwWnlnCm5wMldTV2xZckF0eW1SZ251SXgz
            NTlPK0VGRmRhZ3FkWVlTY2N3MnlrRm8KLS0tIDFmRGM2MXA2N3BGMFp3RitWU1py
            RFJXSkUxeFB2TWtSbG4wcTZ5RUY0Y00Kdh4hrITHFhfy8mi2nrohwHa7aQMzpNJ9
            MJIdUxYUHAMVqTF7vnzWs3gPZy9WFoD91le6M0xe7xrf5gqvsozIEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T09:43:01Z"
    mac: ENC[AES256_GCM,data:m/F6H5P1wvBDmPJUlEl/T2peX1bPnE0ztagyesXZ4pw7DQ5/DvUXya8O5GWNLBOMY7w6URErxDxYBCV/1rgbtPGjBf7TGptxiM1/X//wloQzgqYZPzawo+vQ/8zwOSPzw3J9KlszskCxRvaOedYNa0JqcfasptLnEx16kG0chQ0=,iv:JS9mrRLpqD00qEu6VOmhi+rvX5Fgtu8kSLXpqMLB0jo=,tag:LTIhz/6gH8MNAgNh/HPhUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
