apiVersion: v1
data:
    LD_DB_DATABASE: ENC[AES256_GCM,data:QfU52XPrlVY3dt4W,iv:Mbw61iQKw50Y60fVWHRzXFrIvU7VlGiW0X0AWGsGj/o=,tag:WkK5E/sQd49CDXUzPsTbDw==,type:str]
    LD_DB_ENGINE: ENC[AES256_GCM,data:53iW0Q+C6vkttuyT,iv:UQq963T1ykDx4rBP9Fn3slVSUSOKCsadMCm59CUOuqo=,tag:XaLp7dHqfHx1MwwIzd+tAw==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:58O0GGnXOl4mW/P/HkUAv2GYZbC8KjhjvZMANx+4fP4rZAiu,iv:kJKlrLCuHbKMDQ6pVpvAJnAIu9RCw8aPcGffXyK/qpc=,tag:VCCB0olrHwmfKoxr7fbSuQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:7Beh1U/XMe78ZHf7carBVps5bgxWZPDh,iv:rnmdYU2DMWK9GAIPM6Yqf0fsW43VZrgMvU8uJNW5dGE=,tag:aCSSr/ACsMQT/rrM7GbDIw==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:scMhg3Lsw7M=,iv:8Jbt3aEZbohXjNTZXTl0JuzGB9ETtS0gBltmdG1vCS8=,tag:0HfcC5sDHbjo+cXPyvz8zg==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:aDS1XWx9bFWE5CAS,iv:WhJaz3mPSgc/vdkOV+E03wR5/BNyZGx57XsUoE/Rwi0=,tag:aIA7ZfZCip9hGl1FIt0YAg==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:wNrN/uwL2eY=,iv:Cs74AZ1bp0PsrMM9sXqcAD22nSH/KY0qHSPeyHiWRVo=,tag:0/VyENDVVDksy6Xs3E18OA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:WqCAb/P90+5tjYXy/qIscFFOJsUiPvH2,iv:wxGpNPBKerbJvS0d4nM/DPnQQ1PP3co0taCdxQqrno4=,tag:mBG21nU1GPY1G1Kouvbigw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSDF1OFR5bU8vUmdNdHFy
            RnplRW1kWjMrWG1MWElCRDRmU0pXSWJQM25nCnlPK04reGVYdDZGeXFuTjZWbHQw
            SlZOSW5QVTgxL0syU2VSNWtEK3BLbXcKLS0tIHZpS1NKVE5NcEV5L2M4MXFNOWlh
            L0VHckdkZXhXVjB5V3ZqNnZ0Y2ZpNUUKMsLh2NtAAkkcgVwTC/+OElc6u8mQ8UfJ
            Kj/jHtzKpKibrCd/upC0u4yPvFSKHTpkKhGViCV4NTxwvAHlLWac3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T14:00:51Z"
    mac: ENC[AES256_GCM,data:pbVu+GB3BKKTehu4KS4Hh3AMtpGrSZaDb6qt/sm91vYpI1QMIMobZyKWRkPNiSPBM8Od/3Luc/gRC2xNx6SsJ12+8SEcqNfAMxHhPxKs16Mzu4ZTCapTYION3dgardFqveOCkkKFAqvbMsH45elW4fkwpmu0L8R2EqbYqKhBX0U=,iv:I0d/e6DtcCKmCEco/zTgyMA3NbNKCESLcGLEUbMyG64=,tag:4jXPMCHDIPeMsUjxhAm22w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
