apiVersion: v1
data:
    privateKey: ENC[AES256_GCM,data:VKx3xuYaDJopNfd5X2QrtmKG/ou3B52j/bMqzmiU8ji1A4EvZlzNJF9ogeM5fHXsSZDJhTkCOudMfjFm,iv:mkChJgI/l91YJS0bhfk11BbGulZhBwR0+ICcak7Zamc=,tag:GWQ/RKk13k48dCOJgf7pmw==,type:str]
kind: Secret
metadata:
    name: wireguard-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFRyY0Rvd1BSY2NKTGU4
            a2R2czZvUTRUazJtdmE2OW00cHUzMk1RaFI0CmJuRk9hZU1jSTdYd0krbW11R3Zw
            RkxsQmE5T2M2TE5LYllyMGtRL1lQeEUKLS0tIHlEQzgyUThwcHZvTHdEQ3JkNkpI
            Z2hzTDFpRjY3OThSQlh1VFk4aWJzb2sKiZWUKlMiOwq2qzP4Jmhtel/SDYPfAHaG
            re6gpCANUbGSzs/t98S2tZWK4PISIxnklQYYN17BvRwB0oGNHkYaFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-25T13:03:22Z"
    mac: ENC[AES256_GCM,data:HD3ARBqtTORwk0SreVS6DhgvV5jmfL9y4/2FzbKFCf7LHikpkm9yWeFJDyEYuz2jlH1XvbhrLaoWnAvBVVFrNmvPRCIF0PWPnpGXdKfs46qCtWnpK3iPNFhtfrdsAKcn/3YDviXZW2+KLBkQcAZRwwFHfdfyye+YuAupJWYGXzs=,iv:dJgPtuXYkTEKCK/j0Kt30vAFCJvtDv+Va2ElnOMakN4=,tag:l/dsAecarVzn4gN0yvLGFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
