# Main context (this is the global configuration)
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # homepage
    server {
        listen 443 ssl;  # Listen on port 443 for HTTPS
        server_name robertharte.net homepage.robertharte.net;

        # Proxying requests to docker containers
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # SSL certificate settings
        ssl_certificate /etc/nginx/nginx-certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/nginx-certs/nginx-selfsigned.key;
    }

    # Linkding
    server {
        listen 443 ssl;  # Listen on port 443 for HTTPS
        server_name linkding.robertharte.net robertharte.net/linkding;

        # Proxying requests to linkding containers
        location / {
            proxy_pass http://127.0.0.1:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # SSL certificate settings
        ssl_certificate /etc/nginx/nginx-certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/nginx-certs/nginx-selfsigned.key;
    }
}
