apiVersion: v1
data:
    DB_ENGINE: ENC[AES256_GCM,data:ijgJJh8lIuD8mpYT,iv:FRJjBeWFp18WyJcophbcvEAwVzS/qrSchUiQ1JX4dO4=,tag:qS9zOjjKnZ2jcerZSjSosA==,type:str]
    DEFAULT_EMAIL: ENC[AES256_GCM,data:62hL9hxR+5mXFXABMZz9FMs8WYb3psIOSeWidPimTac=,iv:Lsxp7se9P4XZfuypHQlnqeyZ8Jp2PoDdtYkgswxns0Q=,tag:yT2eldsQg5b+QSlHAQoAfA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:zGvqdSHsd0Q=,iv:DCnJiiqAYZmubRyWiT6DZnIuoX0EXWAn0FbhWMqlyfU=,tag:F5oUKrEyjDyY1sZo0K8F2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PlhnaEL1sqDMGDcXmVpsw8qOg6HJhBZj,iv:RXJ+0CCmngJialcHnaoWkZbzkwfck0kN5BLbehKKrpw=,tag:UIwUbVeVLNH1ZdmKTwrHpQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:h+vtyc/YOWM=,iv:MbPXDplmWfvoD9zwmaaMGGAQnczdGoCXyFa6CGMHXNE=,tag:lHegKjeuv24TmzYj3hMG9Q==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:JIJYpZcy28Na7x3YwjR6hq8AgQxz60t0bedo8kVwC7MpNqB0,iv:8Kv6Lxz/yZbqIW5wqc0WUa2AibK23BnRCiQmRvzNhB8=,tag:FLKTgA1lR/98x6NzAPadeg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:WkpoW2v6TY4=,iv:xontcFXarQFgNQpdiK0hKjf5np70jHaCmtGjvkQ+XCg=,tag:+7QNlv+Kz61w2FU1rf2BMw==,type:str]
kind: Secret
metadata:
    name: mealie-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRWd1VllwaVZjNVZWSjcv
            ZWxnMThmTlFwbTBLRit5b3pyUnIxdmFUeFQ0ClpXRDdxd1hITjNFR25nVlF2WU9X
            VHd2MXl1cHdGMmMzT0lqenlKNW5POU0KLS0tIC94MHRRN20xY0JkbHRkRGNVS21K
            WjJRa01KR3ZCYXpOek1WemZCMkRNZVUKlo33YRp1c+MZVv2NAqPduRLMHbZvLqlR
            qtpwHBrVBdNj/U4CQNXISzYDgFbzZ/uaBiIIkhx4AhiIhRYB/yI5Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T14:02:09Z"
    mac: ENC[AES256_GCM,data:38+p+lnf3HFX1eNIziP13tO/vC6GvXveNU+JNd5+syoJQE9fk5gSx6sZE7bn5s4+FprIsjibMC7pgR42LSXHi1A6o0v7N7rn639CuqrDPJ8vdLjGgOsmxtooy8z/ABL8gGzPOCd6I/hgb1Z43ah3JlCTeoZs+TtRalCamxrwIy0=,iv:VAk5UZmkNoNhJkvv0zmgXR6wSPNPHbbDxxAhjdKUU90=,tag:mmwel4eCzw4jtpRf0MKlfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
