apiVersion: v1
data:
    DB_ENGINE: ENC[AES256_GCM,data:vs8Kmp+eQadl4+AH,iv:7gYHLWjCWxGg4PmXxrxZsSidYuXxxwk5ZuVKbBmYEDM=,tag:NH6yFyUOH+fOMRrq8LppTQ==,type:str]
    DEFAULT_EMAIL: ENC[AES256_GCM,data:kdLzfhgoKQYycnSciA1OVssZ/gMKqaFOEVsIA4ORbig=,iv:kZtE8IDlpDoPbhlYO+x4o+Qk63ra8Q7z68tjF1OptBs=,tag:u8v1kKimOoTAM267PIch3A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:8dU88vYY9lE=,iv:5tDLe1UwUS9skBYuicLvwS7+p5xT6wXKkdaqoRKdzLo=,tag:072MJ/FF/vflxIIOw36cCQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9xcwCdA0rl+D1BxwtmGaLGLc39bbFqBU,iv:LmKaxH1tUo8kWOWaOET5BPjLK4FILquLfca72lYunnc=,tag:RyJjiUbpoQq6OFiXjziWjQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:x7umQIXdtcQ=,iv:soFhcmCxMCsp8cpTQ3zzs4OZC6FBUOiuaU/Pu3LUFZM=,tag:09sWQrSLdnuTZa1WBlIDoA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:xG/m7YxBqFDhGNbB3PiQczy0TY6sfCiVbCFxFP6kYzQ=,iv:NTeemxpvPIkyOMVK3XE0Y6XOfjPE60P9YspMMFS7DGo=,tag:NiwqVd15+UNNJ5b4qEIySQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:724VZ451KSs=,iv:ltKJCgRMNoHWX6IYCIW/x7qB8gmdvl8otmMHQY4uEFE=,tag:PymQn89QIm8g8pWUgsh+Wg==,type:str]
kind: Secret
metadata:
    name: mealie-container-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnZrUE9INW8wbXhJT1gr
            a25zZkF4MitsbERsK3dmbzdTU0ZBU3cxYUJrClk1ZS9KNjZ3OXhnWFR2bExGSGc5
            bXFMb1dlOS9yaHF6UjJKdDF5TVg4OVkKLS0tIER2b0lYTmxWQkNSckxTNkMrRUo5
            NlJxamZEeE5xMzVpQTd3bTBPU0JoZG8KEh94rxmAB5PO8+VpT4P2zE64Qx9xjfaI
            o+fPWPxqgIqhINvFRthawcj4d1O2FH8Q+gqBuW8QLvQi+EXF0pxR6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T10:49:35Z"
    mac: ENC[AES256_GCM,data:Z2p2/sGibeDB/vfQ0gwd7pyzoTsZNCHPxBJGI8Ze1K5V+wCGfp9KTst0sHy2eM+TcC76pGAztGqoDTtjeO5gbNZXniaIEIgQWdCli3h+zxXNSOW3sKVTkiudeJYNM6ZpEb29vRRagI2OzIqXGv+oCUhfK4RHmMJEsSYhOiulB6s=,iv:lVVtyBkjmXQLLO3AzwrwJaG7dEnAm6Uz+2VANval0UY=,tag:U5nq1Tm+VK19IPEzrVgEGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
