apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config-pvc
  labels:
    app: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
