apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:IPEO+DqiEZE=,iv:gQfrAVDohZFp748RhysqGvRWRSdPskrLUTBVbuNnSIM=,tag:N8qhCWjNEFdI+KIBMmm8GQ==,type:str]
kind: Secret
metadata:
    name: grafana-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkM0FxV0NWWkFJam5keDZi
            VjZkSlhqU29BcWxKcWM2cDBISGhYcWhYNWdFCjY3RTBCczBtY2d5am1Ib0cweVhn
            VkFkNkwzK1d0NnhMdXFsOG1YeStyRE0KLS0tIDh5aGxJOTVEb1diSjlIV1FBU0Vq
            NW1NUE1QL0VmMUlHd1RwMEVwQzBodjAKvdWJXyO6Lofg0DZaOaBFFDbFcCANgo7F
            DKy1BDpFNDYJmg6tf6sEVXt0mSMVzs0ihFuY4n07eDjIpV1WYOqTMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T15:12:35Z"
    mac: ENC[AES256_GCM,data:o9iVPtNp2SuIq9XqN8bO5lbNIsz5kZGXJDMreJ2sw4CyAU3X3UOIH3aM9xXD3JWW69qAmu97AAuX1KW6fhbRI4fJebEY2GsiGv8Ly0CkzDa1wpWProuJ0UwfNs/nD8blHBbd8KKAEkTk4C7b8ToivfogBSd/NStB4pc5/veJhT4=,iv:7Hi/NiwFhn9/3n6F5pkV3dU1UvIXyHmlje9BLkmEIjE=,tag:I2Q9o2yX1Oasi0N8zzeGcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
