apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:9ONvRUnloDU1S2o1SQq5abin2l9JYTxdEtbGMQ==,iv:Kwi3tLN1j5Y0R/4rgyII4En7wNr9FicOwj3bwSnNmjc=,tag:R3RFO7sSyOkf7ay/jsvB1g==,type:str]
kind: Secret
metadata:
    name: grafana-env
sops:
    age:
        - recipient: age14tm0dk52g4tce82g5ccxck5jx5zzcm949aek0y04clgwe3vfdg7s5gmsc2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaL2hWY2NadGNuTWx0OUMv
            SEExNnJxaHZhbEpKOTNzQm02MzZYUzZhK0h3Ck1DY0piVGV6WFlVcG80RUhVdmlH
            RDIvTlRoMkZicDdXNSs1SmJ4dmhkclUKLS0tIHloeDI4OUE5SUtaUEloWkt6SUM4
            VHNISTcwQ2dsdm9SckJBckU5U1dMSmcK0tGSiANsBjWmvm2lAMaOD1x6HghjV9ND
            AqAkJTYv2+r/k0lbjP+UyCoGtHNugwZJYiBOuWELy8HVMJ2vynhiYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T15:19:24Z"
    mac: ENC[AES256_GCM,data:Z8o3Mu7Az/E2wafBQoc7ccxH9UcJkkHRsfDAoN/nBUr4CD4/rFiEtydU9r25hbCtZzbgX9L+KjyblkkeRcPqGp7de0+UsWet4b943IvD03hx8LoWpEEA4gB/6NJBUMhqWGcFeDylz7y5SWN2WyHd2nOdt8UDADmvdvYDsBh+h8E=,iv:QWEqGRTlqpq3BflqZMxWOihh8yQe+N6RWImNapZq3cY=,tag:nYcevb/F8PuXBJ/27shVIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
